import User from '../models/User.js';
import Role from '../models/Role.js';
import Department from '../models/Department.js';
import bcrypt from 'bcryptjs';
import logger from '../config/logger.js';
import { asyncHandler } from '../middleware/errorHandler.js';
import { isAdminActor as isAdminByGrant } from '../utils/isAdminActor.js';

/**
 * Staff management controller.
 *
 * Most routes here are open to non-admin managers holding the granular staff
 * permissions (see server/routes/adminRoutes.js), so anything that touches an
 * ACCOUNT rather than a PERSON — credentials, login identity, hard delete — is
 * additionally gated on the caller being an administrator.
 */

// Whether the caller is an administrator (as opposed to a manager who merely
// holds staff permissions). Mirrors the naming rule in middleware/staffAuthority.js:
// the admin guards grant access by role NAME, so an admin-named role is admin.
const isAdminActor = (req) => isAdminByGrant(req?.user);

// Mint a login username that doesn't collide with an existing one.
const generateUniqueUsername = async (role, firstName, lastName) => {
  let candidate = role.generateUsername(firstName, lastName);
  let counter = 1;
  // eslint-disable-next-line no-await-in-loop
  while (await User.findOne({ username: candidate })) {
    candidate = `${role.generateUsername(firstName, lastName)}${counter}`;
    counter += 1;
  }
  return candidate;
};

// Produce a professional-looking employee ID like `EMP-2026-7K3FB`.
// The 5-character suffix is drawn from an unambiguous alphabet (no I/O/0/1)
// so the printed id is easy to read off an ID card. Re-rolls on the off
// chance the random token collides with an existing user.
const EMPLOYEE_ID_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

const randomEmployeeIdToken = () => {
  let token = '';
  for (let i = 0; i < 5; i++) {
    token += EMPLOYEE_ID_ALPHABET.charAt(
      Math.floor(Math.random() * EMPLOYEE_ID_ALPHABET.length),
    );
  }
  return token;
};

const generateNextEmployeeId = async () => {
  const year = new Date().getFullYear();
  for (let attempt = 0; attempt < 10; attempt++) {
    const candidate = `EMP-${year}-${randomEmployeeIdToken()}`;
    const taken = await User.exists({ 'profile.employeeId': candidate });
    if (!taken) return candidate;
  }
  // Extremely unlikely fallback — append milliseconds to guarantee uniqueness.
  return `EMP-${year}-${randomEmployeeIdToken()}${Date.now().toString(36).slice(-3).toUpperCase()}`;
};

// Matches the professional `EMP-YYYY-XXXXX` format. Anything else (e.g. the
// legacy `EMP0001` / `ADMIN001` ids generated by older code) is considered
// stale and will be regenerated on next save.
const PROFESSIONAL_ID_RE = /^EMP-\d{4}-[A-Z2-9]{5,}$/;

// Create new staff member (Admin only)
export const createStaff = asyncHandler(async (req, res) => {
  const { 
    firstName, 
    lastName, 
    email, 
    phone, 
    roleId,
    departmentId,
    username,
    password,
    generateCredentials = false,
    profile = {}
  } = req.body;

  // Validate required fields (lastName and email are optional).
  if (!firstName || !phone || !roleId || !departmentId) {
    return res.status(400).json({
      success: false,
      message: 'Missing required fields: firstName, phone, roleId, and departmentId are required'
    });
  }

  // Check if user already exists — match on email only when one was supplied.
  const dupOr = [{ phone }];
  if (email && email.trim()) dupOr.push({ email: email.toLowerCase().trim() });
  if (username) dupOr.push({ username });
  const existingUser = await User.findOne({ $or: dupOr });

  if (existingUser) {
    return res.status(400).json({ 
      success: false,
      message: 'User with this email, phone, or username already exists' 
    });
  }

  // Get role and validate it exists
  const role = await Role.findById(roleId);
  if (!role || !role.isActive) {
    return res.status(400).json({
      success: false,
      message: 'Invalid or inactive role specified'
    });
  }

  // Get department and validate it exists
  const department = await Department.findById(departmentId);
  if (!department) {
    return res.status(400).json({
      success: false,
      message: 'Invalid department specified'
    });
  }

  // Does this role sign in to the PMS at all? Roles below hierarchy 6 don't by
  // default (housekeeping, kitchen, room attendants), so their staff are
  // personnel records only — tracked for attendance and payroll, with no
  // credentials to issue, leak or reset. A Super Admin can override this per
  // role, which is how front desk keeps the login it needs.
  const wantsLogin = role.allowsLogin();

  let finalUsername, finalPassword;

  if (!wantsLogin) {
    // No credentials at all — not blank ones. `username` stays unset so the
    // sparse unique index skips the record entirely.
    finalUsername = undefined;
    finalPassword = undefined;
  } else if (generateCredentials) {
    finalUsername = await generateUniqueUsername(role, firstName, lastName);
    // Generate password based on role pattern
    finalPassword = role.generatePassword(firstName, lastName);
  } else {
    // Use provided credentials
    if (!username || !password) {
      return res.status(400).json({
        success: false,
        message: 'Username and password are required when not generating credentials'
      });
    }
    finalUsername = username;
    finalPassword = password;
  }

  // Generate employee ID if not provided
  if (!profile.employeeId) {
    profile.employeeId = await generateNextEmployeeId();
  }

  // Add attendance and payroll permissions for Admin and System Admin roles
  let userPermissions = [...(role.permissions || [])];
  
  // Only Admin and System Administrator roles get attendance/payroll management permissions
  if (role.name === 'Admin' || role.name === 'System Administrator') {
    const attendancePayrollPermissions = [
      'manage_attendance',
      'view_attendance',
      'mark_attendance',
      'edit_attendance',
      'delete_attendance',
      'manage_payroll',
      'view_payroll',
      'generate_payroll',
      'approve_payroll',
      'process_payroll_payments',
      'view_payroll_reports'
    ];
    
    // Add permissions that don't already exist
    attendancePayrollPermissions.forEach(permission => {
      if (!userPermissions.includes(permission)) {
        userPermissions.push(permission);
      }
    });
  }

  // Create user data. Email is optional — omit it entirely when blank so the
  // sparse unique index skips this user (storing '' would still collide).
  const userData = {
    hasLoginAccess: wantsLogin,
    phone: phone.trim(),
    firstName: firstName.trim(),
    lastName: (lastName || '').trim(),
    role: roleId,
    department: departmentId,
    permissions: userPermissions,
    isActive: true,
    profile: {
      ...profile,
      joiningDate: profile.joiningDate || new Date(),
      employeeId: profile.employeeId
    },
    createdBy: req.user.id
  };
  if (email && email.trim()) {
    userData.email = email.toLowerCase().trim();
  }
  // Only set credentials when the role has a login; assigning `undefined`
  // would still create the key and trip the sparse index on ''.
  if (wantsLogin) {
    userData.username = finalUsername;
    userData.password = finalPassword;
  }

  // Create new user
  const user = new User(userData);
  await user.save();

  // Populate user data for response
  await user.populate('role department');

  logger.info('Staff member created by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    newUserId: user._id,
    newUsername: user.username,
    role: role.name,
    department: department.name
  });

  // Return user with credentials (only if generated)
  const userResponse = {
    id: user._id,
    username: user.username,
    email: user.email,
    firstName: user.firstName,
    lastName: user.lastName,
    fullName: user.getFullName(),
    role: user.role,
    department: user.department,
    profile: user.profile,
    isActive: user.isActive,
    createdAt: user.createdAt
  };
  
  res.status(201).json({
    success: true,
    data: {
      user: userResponse,
      credentials: (wantsLogin && generateCredentials) ? {
        username: finalUsername,
        password: finalPassword
      } : undefined,
      // Lets the UI say "no login for this role" instead of silently showing
      // an empty credentials panel.
      hasLoginAccess: wantsLogin
    },
    message: wantsLogin
      ? 'Staff member created successfully'
      : 'Staff member added. This role has no app login, so no credentials were issued.'
  });
});

// Get all staff members (Admin only)
export const getAllStaff = asyncHandler(async (req, res) => {
  try {
    const { 
      page = 1, 
      limit = 10, 
      department, 
      role, 
      isActive, 
      search 
    } = req.query;

    // Build filter query
    const filter = {};
    
    if (department) filter.department = department;
    if (role) filter.role = role;
    if (isActive !== undefined) filter.isActive = isActive === 'true';
    
    if (search) {
      filter.$or = [
        { firstName: { $regex: search, $options: 'i' } },
        { lastName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { username: { $regex: search, $options: 'i' } }
      ];
    }

    // Use simple find instead of paginate if paginate is causing issues
    const users = await User.find(filter)
      .select('-password -loginAttempts -lockUntil')
      .populate('role', 'name hierarchy permissions')
      .populate('department', 'name')
      .populate('createdBy', 'username firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit));

    const total = await User.countDocuments(filter);

    res.json({
      success: true,
      data: {
        docs: users,
        totalDocs: total,
        limit: parseInt(limit),
        page: parseInt(page),
        totalPages: Math.ceil(total / parseInt(limit)),
        hasNextPage: parseInt(page) < Math.ceil(total / parseInt(limit)),
        hasPrevPage: parseInt(page) > 1
      },
      message: 'Staff members fetched successfully'
    });
  } catch (error) {
    logger.error('Error fetching staff members:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch staff members',
      error: error.message
    });
  }
});

// Get staff member by ID (Admin only)
export const getStaffById = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const user = await User.findById(id)
    .select('-password -loginAttempts -lockUntil')
    .populate('role department createdBy', 'name username firstName lastName hierarchy permissions');

  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  res.json({
    success: true,
    data: user,
    message: 'Staff member details fetched successfully'
  });
});

// Update staff member (Admin only)
export const updateStaff = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const updates = req.body;
  // Set when a role change moves the staff member across the login threshold.
  let issuedCredentials = null;
  let revokeCredentials = false;

  // Remove sensitive fields that shouldn't be updated directly
  delete updates.password;
  delete updates.loginAttempts;
  delete updates.lockUntil;
  delete updates.createdBy;
  delete updates._id;
  // The login identity is an admin-only field. A manager with `edit_staff` may
  // maintain a staff member's details, but changing the name they sign in with
  // is account administration, not staff administration — and it would let a
  // manager quietly retarget an account. `hasLoginAccess` is derived from the
  // role below, never accepted from the client.
  delete updates.hasLoginAccess;
  if (!isAdminActor(req)) {
    delete updates.username;
  }

  // The staff form (create AND edit) sends roleId/departmentId, but the User
  // document stores them as `role`/`department`. Without this mapping the edit
  // path validated the wrong keys and Object.assign wrote non-schema fields
  // that Mongoose silently dropped — so changing a staff member's role or
  // department never persisted. Normalise here so edits actually save.
  if (updates.roleId !== undefined) { updates.role = updates.roleId; delete updates.roleId; }
  if (updates.departmentId !== undefined) { updates.department = updates.departmentId; delete updates.departmentId; }
  // Not schema fields — drop so they don't linger on the doc.
  delete updates.generateCredentials;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // If role is being updated, validate it
  if (updates.role) {
    const role = await Role.findById(updates.role);
    if (!role || !role.isActive) {
      return res.status(400).json({
        success: false,
        message: 'Invalid or inactive role specified'
      });
    }
    updates.permissions = role.permissions || [];

    // Login access follows the role. Moving someone up to a role that signs in
    // has to mint credentials (there are none to reuse); moving them down to a
    // personnel-only role revokes them, so the account can no longer be used.
    const nowAllowsLogin = role.allowsLogin();
    if (nowAllowsLogin && !user.hasLoginAccess) {
      updates.hasLoginAccess = true;
      updates.username = await generateUniqueUsername(role, user.firstName, user.lastName);
      updates.password = role.generatePassword(user.firstName, user.lastName);
      issuedCredentials = { username: updates.username, password: updates.password };
    } else if (!nowAllowsLogin && user.hasLoginAccess !== false) {
      updates.hasLoginAccess = false;
      // Unset rather than blank: '' would collide on the sparse unique index
      // the moment a second staff member is demoted.
      revokeCredentials = true;
    }
  }

  // If department is being updated, validate it
  if (updates.department) {
    const department = await Department.findById(updates.department);
    if (!department) {
      return res.status(400).json({
        success: false,
        message: 'Invalid department specified'
      });
    }
  }

  // If the form sent an empty employeeId, keep the existing value as-is so
  // we don't accidentally wipe it.
  if (updates.profile) {
    const incoming = updates.profile.employeeId;
    const existing = user.profile?.employeeId;
    if (!incoming && existing) {
      updates.profile.employeeId = existing;
    }
  }

  // Update user
  Object.assign(user, updates);

  // Demoted to a personnel-only role: drop the credentials entirely. `$unset`
  // (not '') so the sparse unique index ignores the document.
  if (revokeCredentials) {
    user.username = undefined;
    user.password = undefined;
    user.markModified('username');
    user.markModified('password');
  }

  if (!user.profile) user.profile = {};

  // Generate (or upgrade) the employee ID:
  //   - missing → fresh professional id
  //   - legacy format (e.g. `EMP0001`, `ADMIN001`) → migrate to new format
  //   - already professional → leave it alone (it's printed on ID cards)
  const currentId = user.profile.employeeId || '';
  if (!currentId || !PROFESSIONAL_ID_RE.test(currentId)) {
    user.profile.employeeId = await generateNextEmployeeId();
    user.markModified('profile');
  }

  await user.save();

  // The unset has to reach Mongo explicitly — assigning `undefined` marks the
  // path modified but `save()` won't emit a $unset for it on an existing doc.
  if (revokeCredentials) {
    await User.collection.updateOne(
      { _id: user._id },
      { $unset: { username: '', password: '' } },
    );
  }

  // Populate updated user
  await user.populate('role department');

  logger.info('Staff member updated by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    updatedUserId: user._id,
    updatedUsername: user.username,
    updates: Object.keys(updates),
    loginAccessChanged: revokeCredentials ? 'revoked' : (issuedCredentials ? 'granted' : 'unchanged')
  });

  res.json({
    success: true,
    data: user,
    // Present only when a role change just minted a login — the UI shows these
    // once, exactly as it does after creating a staff member.
    credentials: issuedCredentials,
    message: revokeCredentials
      ? 'Staff member updated. This role has no app login, so their credentials were removed.'
      : (issuedCredentials
        ? 'Staff member updated. This role signs in, so new login credentials were issued.'
        : 'Staff member updated successfully')
  });
});

// Reset staff password (Admin only)
export const resetStaffPassword = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { newPassword, generatePassword = false } = req.body;

  // Credentials are account administration, not staff administration. A manager
  // with `edit_staff` may maintain the person's record, but handing them
  // password resets means they can take over any account they can see —
  // including, over time, one that outranks them.
  if (!isAdminActor(req)) {
    return res.status(403).json({
      success: false,
      message: 'Access denied. Only an administrator can reset a staff password.'
    });
  }

  const user = await User.findById(id).populate('role');
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // Nothing to reset on a personnel-only record — it has no credentials.
  if (user.hasLoginAccess === false) {
    return res.status(400).json({
      success: false,
      message: 'This staff member has no app login, so there is no password to reset.'
    });
  }

  let finalPassword;
  
  if (generatePassword) {
    // Generate password based on role pattern
    finalPassword = user.role.generatePassword(user.firstName, user.lastName);
  } else {
    if (!newPassword) {
      return res.status(400).json({
        success: false,
        message: 'New password is required when not generating password'
      });
    }
    finalPassword = newPassword;
  }

  // Update password
  user.password = finalPassword;
  await user.save();

  logger.info('Staff password reset by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    targetUserId: user._id,
    targetUsername: user.username
  });

  res.json({
    success: true,
    data: {
      username: user.username,
      newPassword: finalPassword
    },
    message: 'Password reset successfully'
  });
});

// Deactivate/Activate staff member (Admin only)
export const toggleStaffStatus = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { isActive } = req.body;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // Prevent admin from deactivating themselves
  if (user._id.toString() === req.user.id) {
    return res.status(400).json({
      success: false,
      message: 'You cannot deactivate your own account'
    });
  }

  user.isActive = isActive;
  await user.save();

  logger.info('Staff status toggled by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    targetUserId: user._id,
    targetUsername: user.username,
    newStatus: isActive ? 'active' : 'inactive'
  });

  res.json({
    success: true,
    data: { isActive: user.isActive },
    message: `Staff member ${isActive ? 'activated' : 'deactivated'} successfully`
  });
});

// Delete staff member (Admin only)
export const deleteStaff = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // Prevent admin from deleting themselves
  if (user._id.toString() === req.user.id) {
    return res.status(400).json({
      success: false,
      message: 'You cannot delete your own account'
    });
  }

  await User.findByIdAndDelete(id);

  logger.warn('Staff member deleted by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    deletedUserId: user._id,
    deletedUsername: user.username,
    deletedUserEmail: user.email
  });

  res.json({
    success: true,
    message: 'Staff member deleted successfully'
  });
});

// Get staff statistics (Admin only)
export const getStaffStats = asyncHandler(async (req, res) => {
  const totalStaff = await User.countDocuments();
  const activeStaff = await User.countDocuments({ isActive: true });
  const inactiveStaff = await User.countDocuments({ isActive: false });

  // Staff by department
  const staffByDepartment = await User.aggregate([
    {
      $lookup: {
        from: 'departments',
        localField: 'department',
        foreignField: '_id',
        as: 'departmentInfo'
      }
    },
    {
      $unwind: '$departmentInfo'
    },
    {
      $group: {
        _id: '$departmentInfo.name',
        count: { $sum: 1 }
      }
    }
  ]);

  // Staff by role
  const staffByRole = await User.aggregate([
    {
      $lookup: {
        from: 'roles',
        localField: 'role',
        foreignField: '_id',
        as: 'roleInfo'
      }
    },
    {
      $unwind: '$roleInfo'
    },
    {
      $group: {
        _id: '$roleInfo.name',
        count: { $sum: 1 }
      }
    }
  ]);

  // Recent joinings (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const recentJoinings = await User.countDocuments({
    createdAt: { $gte: thirtyDaysAgo }
  });

  res.json({
    success: true,
    data: {
      totalStaff,
      activeStaff,
      inactiveStaff,
      staffByDepartment,
      staffByRole,
      recentJoinings
    },
    message: 'Staff statistics fetched successfully'
  });
});
