import User from '../models/User.js';
import Role from '../models/Role.js';
import Department from '../models/Department.js';
import bcrypt from 'bcryptjs';
import logger from '../config/logger.js';
import { asyncHandler } from '../middleware/errorHandler.js';

/**
 * Admin-only staff management controller
 * Only administrators can create, manage, and assign roles to staff
 */

// Produce a professional-looking employee ID like `EMP-2026-7K3FB`.
// The 5-character suffix is drawn from an unambiguous alphabet (no I/O/0/1)
// so the printed id is easy to read off an ID card. Re-rolls on the off
// chance the random token collides with an existing user.
const EMPLOYEE_ID_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

const randomEmployeeIdToken = () => {
  let token = '';
  for (let i = 0; i < 5; i++) {
    token += EMPLOYEE_ID_ALPHABET.charAt(
      Math.floor(Math.random() * EMPLOYEE_ID_ALPHABET.length),
    );
  }
  return token;
};

const generateNextEmployeeId = async () => {
  const year = new Date().getFullYear();
  for (let attempt = 0; attempt < 10; attempt++) {
    const candidate = `EMP-${year}-${randomEmployeeIdToken()}`;
    const taken = await User.exists({ 'profile.employeeId': candidate });
    if (!taken) return candidate;
  }
  // Extremely unlikely fallback — append milliseconds to guarantee uniqueness.
  return `EMP-${year}-${randomEmployeeIdToken()}${Date.now().toString(36).slice(-3).toUpperCase()}`;
};

// Matches the professional `EMP-YYYY-XXXXX` format. Anything else (e.g. the
// legacy `EMP0001` / `ADMIN001` ids generated by older code) is considered
// stale and will be regenerated on next save.
const PROFESSIONAL_ID_RE = /^EMP-\d{4}-[A-Z2-9]{5,}$/;

// Create new staff member (Admin only)
export const createStaff = asyncHandler(async (req, res) => {
  const { 
    firstName, 
    lastName, 
    email, 
    phone, 
    roleId,
    departmentId,
    username,
    password,
    generateCredentials = false,
    profile = {}
  } = req.body;

  // Validate required fields
  if (!firstName || !lastName || !email || !phone || !roleId || !departmentId) {
    return res.status(400).json({ 
      success: false, 
      message: 'Missing required fields: firstName, lastName, email, phone, roleId, and departmentId are required' 
    });
  }

  // Check if user already exists
  const existingUser = await User.findOne({
    $or: [{ email: email.toLowerCase() }, { phone }, { username }]
  });

  if (existingUser) {
    return res.status(400).json({ 
      success: false,
      message: 'User with this email, phone, or username already exists' 
    });
  }

  // Get role and validate it exists
  const role = await Role.findById(roleId);
  if (!role || !role.isActive) {
    return res.status(400).json({
      success: false,
      message: 'Invalid or inactive role specified'
    });
  }

  // Get department and validate it exists
  const department = await Department.findById(departmentId);
  if (!department) {
    return res.status(400).json({
      success: false,
      message: 'Invalid department specified'
    });
  }

  // Check if role can have user account
  if (!role.userAccountSettings?.canHaveUserAccount) {
    return res.status(400).json({
      success: false,
      message: 'This role cannot have a user account'
    });
  }

  let finalUsername, finalPassword;
  
  if (generateCredentials) {
    // Generate username based on role pattern
    finalUsername = role.generateUsername(firstName, lastName);
    
    // Check if username exists and make it unique
    let usernameExists = await User.findOne({ username: finalUsername });
    let counter = 1;
    while (usernameExists) {
      finalUsername = `${role.generateUsername(firstName, lastName)}${counter}`;
      usernameExists = await User.findOne({ username: finalUsername });
      counter++;
    }
    
    // Generate password based on role pattern
    finalPassword = role.generatePassword(firstName, lastName);
  } else {
    // Use provided credentials
    if (!username || !password) {
      return res.status(400).json({
        success: false,
        message: 'Username and password are required when not generating credentials'
      });
    }
    finalUsername = username;
    finalPassword = password;
  }

  // Generate employee ID if not provided
  if (!profile.employeeId) {
    profile.employeeId = await generateNextEmployeeId();
  }

  // Add attendance and payroll permissions for Admin and System Admin roles
  let userPermissions = [...(role.permissions || [])];
  
  // Only Admin and System Administrator roles get attendance/payroll management permissions
  if (role.name === 'Admin' || role.name === 'System Administrator') {
    const attendancePayrollPermissions = [
      'manage_attendance',
      'view_attendance',
      'mark_attendance',
      'edit_attendance',
      'delete_attendance',
      'manage_payroll',
      'view_payroll',
      'generate_payroll',
      'approve_payroll',
      'process_payroll_payments',
      'view_payroll_reports'
    ];
    
    // Add permissions that don't already exist
    attendancePayrollPermissions.forEach(permission => {
      if (!userPermissions.includes(permission)) {
        userPermissions.push(permission);
      }
    });
  }

  // Create user data
  const userData = {
    username: finalUsername,
    password: finalPassword,
    email: email.toLowerCase().trim(),
    phone: phone.trim(),
    firstName: firstName.trim(),
    lastName: lastName.trim(),
    role: roleId,
    department: departmentId,
    permissions: userPermissions,
    isActive: true,
    profile: {
      ...profile,
      joiningDate: profile.joiningDate || new Date(),
      employeeId: profile.employeeId
    },
    createdBy: req.user.id
  };

  // Create new user
  const user = new User(userData);
  await user.save();

  // Populate user data for response
  await user.populate('role department');

  logger.info('Staff member created by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    newUserId: user._id,
    newUsername: user.username,
    role: role.name,
    department: department.name
  });

  // Return user with credentials (only if generated)
  const userResponse = {
    id: user._id,
    username: user.username,
    email: user.email,
    firstName: user.firstName,
    lastName: user.lastName,
    fullName: user.getFullName(),
    role: user.role,
    department: user.department,
    profile: user.profile,
    isActive: user.isActive,
    createdAt: user.createdAt
  };
  
  res.status(201).json({
    success: true,
    data: {
      user: userResponse,
      credentials: generateCredentials ? { 
        username: finalUsername, 
        password: finalPassword 
      } : undefined
    },
    message: 'Staff member created successfully'
  });
});

// Get all staff members (Admin only)
export const getAllStaff = asyncHandler(async (req, res) => {
  try {
    const { 
      page = 1, 
      limit = 10, 
      department, 
      role, 
      isActive, 
      search 
    } = req.query;

    // Build filter query
    const filter = {};
    
    if (department) filter.department = department;
    if (role) filter.role = role;
    if (isActive !== undefined) filter.isActive = isActive === 'true';
    
    if (search) {
      filter.$or = [
        { firstName: { $regex: search, $options: 'i' } },
        { lastName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { username: { $regex: search, $options: 'i' } }
      ];
    }

    // Use simple find instead of paginate if paginate is causing issues
    const users = await User.find(filter)
      .select('-password -loginAttempts -lockUntil')
      .populate('role', 'name hierarchy permissions')
      .populate('department', 'name')
      .populate('createdBy', 'username firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit));

    const total = await User.countDocuments(filter);

    res.json({
      success: true,
      data: {
        docs: users,
        totalDocs: total,
        limit: parseInt(limit),
        page: parseInt(page),
        totalPages: Math.ceil(total / parseInt(limit)),
        hasNextPage: parseInt(page) < Math.ceil(total / parseInt(limit)),
        hasPrevPage: parseInt(page) > 1
      },
      message: 'Staff members fetched successfully'
    });
  } catch (error) {
    logger.error('Error fetching staff members:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch staff members',
      error: error.message
    });
  }
});

// Get staff member by ID (Admin only)
export const getStaffById = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const user = await User.findById(id)
    .select('-password -loginAttempts -lockUntil')
    .populate('role department createdBy', 'name username firstName lastName hierarchy permissions');

  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  res.json({
    success: true,
    data: user,
    message: 'Staff member details fetched successfully'
  });
});

// Update staff member (Admin only)
export const updateStaff = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const updates = req.body;

  // Remove sensitive fields that shouldn't be updated directly
  delete updates.password;
  delete updates.loginAttempts;
  delete updates.lockUntil;
  delete updates.createdBy;
  delete updates._id;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // If role is being updated, validate it
  if (updates.role) {
    const role = await Role.findById(updates.role);
    if (!role || !role.isActive) {
      return res.status(400).json({
        success: false,
        message: 'Invalid or inactive role specified'
      });
    }
    updates.permissions = role.permissions || [];
  }

  // If department is being updated, validate it
  if (updates.department) {
    const department = await Department.findById(updates.department);
    if (!department) {
      return res.status(400).json({
        success: false,
        message: 'Invalid department specified'
      });
    }
  }

  // If the form sent an empty employeeId, keep the existing value as-is so
  // we don't accidentally wipe it.
  if (updates.profile) {
    const incoming = updates.profile.employeeId;
    const existing = user.profile?.employeeId;
    if (!incoming && existing) {
      updates.profile.employeeId = existing;
    }
  }

  // Update user
  Object.assign(user, updates);

  if (!user.profile) user.profile = {};

  // Generate (or upgrade) the employee ID:
  //   - missing → fresh professional id
  //   - legacy format (e.g. `EMP0001`, `ADMIN001`) → migrate to new format
  //   - already professional → leave it alone (it's printed on ID cards)
  const currentId = user.profile.employeeId || '';
  if (!currentId || !PROFESSIONAL_ID_RE.test(currentId)) {
    user.profile.employeeId = await generateNextEmployeeId();
    user.markModified('profile');
  }

  await user.save();

  // Populate updated user
  await user.populate('role department');

  logger.info('Staff member updated by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    updatedUserId: user._id,
    updatedUsername: user.username,
    updates: Object.keys(updates)
  });

  res.json({
    success: true,
    data: user,
    message: 'Staff member updated successfully'
  });
});

// Reset staff password (Admin only)
export const resetStaffPassword = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { newPassword, generatePassword = false } = req.body;

  const user = await User.findById(id).populate('role');
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  let finalPassword;
  
  if (generatePassword) {
    // Generate password based on role pattern
    finalPassword = user.role.generatePassword(user.firstName, user.lastName);
  } else {
    if (!newPassword) {
      return res.status(400).json({
        success: false,
        message: 'New password is required when not generating password'
      });
    }
    finalPassword = newPassword;
  }

  // Update password
  user.password = finalPassword;
  await user.save();

  logger.info('Staff password reset by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    targetUserId: user._id,
    targetUsername: user.username
  });

  res.json({
    success: true,
    data: {
      username: user.username,
      newPassword: finalPassword
    },
    message: 'Password reset successfully'
  });
});

// Deactivate/Activate staff member (Admin only)
export const toggleStaffStatus = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { isActive } = req.body;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // Prevent admin from deactivating themselves
  if (user._id.toString() === req.user.id) {
    return res.status(400).json({
      success: false,
      message: 'You cannot deactivate your own account'
    });
  }

  user.isActive = isActive;
  await user.save();

  logger.info('Staff status toggled by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    targetUserId: user._id,
    targetUsername: user.username,
    newStatus: isActive ? 'active' : 'inactive'
  });

  res.json({
    success: true,
    data: { isActive: user.isActive },
    message: `Staff member ${isActive ? 'activated' : 'deactivated'} successfully`
  });
});

// Delete staff member (Admin only)
export const deleteStaff = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const user = await User.findById(id);
  if (!user) {
    return res.status(404).json({
      success: false,
      message: 'Staff member not found'
    });
  }

  // Prevent admin from deleting themselves
  if (user._id.toString() === req.user.id) {
    return res.status(400).json({
      success: false,
      message: 'You cannot delete your own account'
    });
  }

  await User.findByIdAndDelete(id);

  logger.warn('Staff member deleted by admin', {
    adminId: req.user.id,
    adminUsername: req.user.username,
    deletedUserId: user._id,
    deletedUsername: user.username,
    deletedUserEmail: user.email
  });

  res.json({
    success: true,
    message: 'Staff member deleted successfully'
  });
});

// Get staff statistics (Admin only)
export const getStaffStats = asyncHandler(async (req, res) => {
  const totalStaff = await User.countDocuments();
  const activeStaff = await User.countDocuments({ isActive: true });
  const inactiveStaff = await User.countDocuments({ isActive: false });

  // Staff by department
  const staffByDepartment = await User.aggregate([
    {
      $lookup: {
        from: 'departments',
        localField: 'department',
        foreignField: '_id',
        as: 'departmentInfo'
      }
    },
    {
      $unwind: '$departmentInfo'
    },
    {
      $group: {
        _id: '$departmentInfo.name',
        count: { $sum: 1 }
      }
    }
  ]);

  // Staff by role
  const staffByRole = await User.aggregate([
    {
      $lookup: {
        from: 'roles',
        localField: 'role',
        foreignField: '_id',
        as: 'roleInfo'
      }
    },
    {
      $unwind: '$roleInfo'
    },
    {
      $group: {
        _id: '$roleInfo.name',
        count: { $sum: 1 }
      }
    }
  ]);

  // Recent joinings (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const recentJoinings = await User.countDocuments({
    createdAt: { $gte: thirtyDaysAgo }
  });

  res.json({
    success: true,
    data: {
      totalStaff,
      activeStaff,
      inactiveStaff,
      staffByDepartment,
      staffByRole,
      recentJoinings
    },
    message: 'Staff statistics fetched successfully'
  });
});
